# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vedayu-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/MLVision', '6.25.0'
  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'YandexMapKit'
end
